/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_mpcc_2d_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[13] = 
  {7, 3, 0, 3, 6, 7, 1, 3,
  5, 1, 3, 5, 6};
static const casadi_int casadi_s1[17] = 
  {3, 7, 0, 0, 2, 2, 4, 4,
  6, 7, 0, 1, 0, 1, 0, 1,
  2};
static const casadi_int casadi_s2[24] = 
  {7, 3, 0, 6, 12, 18, 0, 1,
  2, 3, 4, 5, 0, 1, 2, 3,
  4, 5, 0, 1, 2, 3, 4, 6};
static const casadi_int casadi_s3[21] = 
  {7, 3, 0, 5, 10, 15, 0, 1,
  2, 3, 4, 0, 1, 2, 3, 4,
  0, 1, 2, 3, 4};
static const casadi_int casadi_s4[3] = {7, 1, 1};
static const casadi_int casadi_s5[3] = {7, 7, 1};
static const casadi_int casadi_s6[3] = {7, 3, 1};
static const casadi_int casadi_s7[3] = {3, 1, 1};
static const casadi_int casadi_s8[3] = {4, 1, 1};
static const casadi_int casadi_s9[45] = 
  {7, 7, 0, 5, 10, 15, 20, 25,
  30, 35, 0, 1, 2, 3, 4, 0,
  1, 2, 3, 4, 0, 1, 2, 3,
  4, 0, 1, 2, 3, 4, 0, 1,
  2, 3, 4, 0, 1, 2, 3, 4,
  0, 1, 2, 3, 4};

static const casadi_real casadi_zeros[49] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* quadrotor_mpcc_2d_expl_vde_forw:(i0[7],i1[7x7],i2[7x3],i3[3],i4[4])->(o0[7],o1[7x7,35nz],o2[7x3,18nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, *w13=w+98, *w14=w+105, w15, w16;
  casadi_real *w18=w+114, w19, w20, *w21=w+118, *w22=w+122, *w23=w+126, *w24=w+129, *w25=w+132, *w27=w+171, *w28=w+176, *w29=w+181, *w30=w+186;
  casadi_real *w31=w+201;
  const casadi_real *cs, *wr07, *wr08, *wr09, *wr10, *wr11, *wr12, *wr13, *wr14, *wr26;
  /* #0: @0 = input[0][1] */
  w00 = arg[0] ? arg[0][1] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #2: @0 = input[0][4] */
  w00 = arg[0] ? arg[0][4] : 0;
  /* #3: @1 = sin(@0) */
  w01 = sin( w00 );
  /* #4: @2 = input[3][0] */
  w02 = arg[3] ? arg[3][0] : 0;
  /* #5: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #6: @4 = (@2+@3) */
  w04  = (w02+w03);
  /* #7: @5 = (@1*@4) */
  w05  = (w01*w04);
  /* #8: @6 = 0.027 */
  w06 = 2.7000000000000000e-02;
  /* #9: @5 = (@5/@6) */
  w05 /= w06;
  /* #10: output[0][1] = @5 */
  if (res[0]) res[0][1] = w05;
  /* #11: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #12: output[0][2] = @5 */
  if (res[0]) res[0][2] = w05;
  /* #13: @0 = cos(@0) */
  w00 = cos( w00 );
  /* #14: @5 = (@0*@4) */
  w05  = (w00*w04);
  /* #15: @5 = (@5/@6) */
  w05 /= w06;
  /* #16: @6 = 9.8 */
  w06 = 9.8000000000000007e+00;
  /* #17: @5 = (@5-@6) */
  w05 -= w06;
  /* #18: output[0][3] = @5 */
  if (res[0]) res[0][3] = w05;
  /* #19: @5 = input[0][5] */
  w05 = arg[0] ? arg[0][5] : 0;
  /* #20: output[0][4] = @5 */
  if (res[0]) res[0][4] = w05;
  /* #21: @5 = 0.0397 */
  w05 = 3.9699999999999999e-02;
  /* #22: @3 = (@3-@2) */
  w03 -= w02;
  /* #23: @3 = (@5*@3) */
  w03  = (w05*w03);
  /* #24: @2 = 1.4e-05 */
  w02 = 1.4000000000000000e-05;
  /* #25: @3 = (@3/@2) */
  w03 /= w02;
  /* #26: @2 = 1.41421 */
  w02 = 1.4142135623730951e+00;
  /* #27: @3 = (@3/@2) */
  w03 /= w02;
  /* #28: output[0][5] = @3 */
  if (res[0]) res[0][5] = w03;
  /* #29: @3 = input[3][2] */
  w03 = arg[3] ? arg[3][2] : 0;
  /* #30: output[0][6] = @3 */
  if (res[0]) res[0][6] = w03;
  /* #31: @7 = input[1][0] */
  wr07 = arg[1] ? arg[1] : casadi_zeros;
  /* #32: {@8, @9, @10, @11, @12, @13, @14} = horzsplit(@7) */
  wr08 = wr07;
  wr09 = wr07+7;
  wr10 = wr07+14;
  wr11 = wr07+21;
  wr12 = wr07+28;
  wr13 = wr07+35;
  wr14 = wr07+42;
  /* #33: {NULL, @3, NULL, @2, @6, @15, NULL} = vertsplit(@8) */
  w03 = wr08[1];
  w02 = wr08[3];
  w06 = wr08[4];
  w15 = wr08[5];
  /* #34: output[1][0] = @3 */
  if (res[1]) res[1][0] = w03;
  /* #35: @3 = 37.037 */
  w03 = 3.7037037037037038e+01;
  /* #36: @16 = (@0*@6) */
  w16  = (w00*w06);
  /* #37: @16 = (@4*@16) */
  w16  = (w04*w16);
  /* #38: @16 = (@3*@16) */
  w16  = (w03*w16);
  /* #39: output[1][1] = @16 */
  if (res[1]) res[1][1] = w16;
  /* #40: output[1][2] = @2 */
  if (res[1]) res[1][2] = w02;
  /* #41: @6 = (@1*@6) */
  w06  = (w01*w06);
  /* #42: @6 = (@4*@6) */
  w06  = (w04*w06);
  /* #43: @6 = (@3*@6) */
  w06  = (w03*w06);
  /* #44: @6 = (-@6) */
  w06 = (- w06 );
  /* #45: output[1][3] = @6 */
  if (res[1]) res[1][3] = w06;
  /* #46: output[1][4] = @15 */
  if (res[1]) res[1][4] = w15;
  /* #47: {NULL, @15, NULL, @6, @2, @16, NULL} = vertsplit(@9) */
  w15 = wr09[1];
  w06 = wr09[3];
  w02 = wr09[4];
  w16 = wr09[5];
  /* #48: output[1][5] = @15 */
  if (res[1]) res[1][5] = w15;
  /* #49: @15 = (@0*@2) */
  w15  = (w00*w02);
  /* #50: @15 = (@4*@15) */
  w15  = (w04*w15);
  /* #51: @15 = (@3*@15) */
  w15  = (w03*w15);
  /* #52: output[1][6] = @15 */
  if (res[1]) res[1][6] = w15;
  /* #53: output[1][7] = @6 */
  if (res[1]) res[1][7] = w06;
  /* #54: @2 = (@1*@2) */
  w02  = (w01*w02);
  /* #55: @2 = (@4*@2) */
  w02  = (w04*w02);
  /* #56: @2 = (@3*@2) */
  w02  = (w03*w02);
  /* #57: @2 = (-@2) */
  w02 = (- w02 );
  /* #58: output[1][8] = @2 */
  if (res[1]) res[1][8] = w02;
  /* #59: output[1][9] = @16 */
  if (res[1]) res[1][9] = w16;
  /* #60: {NULL, @16, NULL, @2, @6, @15, NULL} = vertsplit(@10) */
  w16 = wr10[1];
  w02 = wr10[3];
  w06 = wr10[4];
  w15 = wr10[5];
  /* #61: output[1][10] = @16 */
  if (res[1]) res[1][10] = w16;
  /* #62: @16 = (@0*@6) */
  w16  = (w00*w06);
  /* #63: @16 = (@4*@16) */
  w16  = (w04*w16);
  /* #64: @16 = (@3*@16) */
  w16  = (w03*w16);
  /* #65: output[1][11] = @16 */
  if (res[1]) res[1][11] = w16;
  /* #66: output[1][12] = @2 */
  if (res[1]) res[1][12] = w02;
  /* #67: @6 = (@1*@6) */
  w06  = (w01*w06);
  /* #68: @6 = (@4*@6) */
  w06  = (w04*w06);
  /* #69: @6 = (@3*@6) */
  w06  = (w03*w06);
  /* #70: @6 = (-@6) */
  w06 = (- w06 );
  /* #71: output[1][13] = @6 */
  if (res[1]) res[1][13] = w06;
  /* #72: output[1][14] = @15 */
  if (res[1]) res[1][14] = w15;
  /* #73: {NULL, @15, NULL, @6, @2, @16, NULL} = vertsplit(@11) */
  w15 = wr11[1];
  w06 = wr11[3];
  w02 = wr11[4];
  w16 = wr11[5];
  /* #74: output[1][15] = @15 */
  if (res[1]) res[1][15] = w15;
  /* #75: @15 = (@0*@2) */
  w15  = (w00*w02);
  /* #76: @15 = (@4*@15) */
  w15  = (w04*w15);
  /* #77: @15 = (@3*@15) */
  w15  = (w03*w15);
  /* #78: output[1][16] = @15 */
  if (res[1]) res[1][16] = w15;
  /* #79: output[1][17] = @6 */
  if (res[1]) res[1][17] = w06;
  /* #80: @2 = (@1*@2) */
  w02  = (w01*w02);
  /* #81: @2 = (@4*@2) */
  w02  = (w04*w02);
  /* #82: @2 = (@3*@2) */
  w02  = (w03*w02);
  /* #83: @2 = (-@2) */
  w02 = (- w02 );
  /* #84: output[1][18] = @2 */
  if (res[1]) res[1][18] = w02;
  /* #85: output[1][19] = @16 */
  if (res[1]) res[1][19] = w16;
  /* #86: {NULL, @16, NULL, @2, @6, @15, NULL} = vertsplit(@12) */
  w16 = wr12[1];
  w02 = wr12[3];
  w06 = wr12[4];
  w15 = wr12[5];
  /* #87: output[1][20] = @16 */
  if (res[1]) res[1][20] = w16;
  /* #88: @16 = (@0*@6) */
  w16  = (w00*w06);
  /* #89: @16 = (@4*@16) */
  w16  = (w04*w16);
  /* #90: @16 = (@3*@16) */
  w16  = (w03*w16);
  /* #91: output[1][21] = @16 */
  if (res[1]) res[1][21] = w16;
  /* #92: output[1][22] = @2 */
  if (res[1]) res[1][22] = w02;
  /* #93: @6 = (@1*@6) */
  w06  = (w01*w06);
  /* #94: @6 = (@4*@6) */
  w06  = (w04*w06);
  /* #95: @6 = (@3*@6) */
  w06  = (w03*w06);
  /* #96: @6 = (-@6) */
  w06 = (- w06 );
  /* #97: output[1][23] = @6 */
  if (res[1]) res[1][23] = w06;
  /* #98: output[1][24] = @15 */
  if (res[1]) res[1][24] = w15;
  /* #99: {NULL, @15, NULL, @6, @2, @16, NULL} = vertsplit(@13) */
  w15 = wr13[1];
  w06 = wr13[3];
  w02 = wr13[4];
  w16 = wr13[5];
  /* #100: output[1][25] = @15 */
  if (res[1]) res[1][25] = w15;
  /* #101: @15 = (@0*@2) */
  w15  = (w00*w02);
  /* #102: @15 = (@4*@15) */
  w15  = (w04*w15);
  /* #103: @15 = (@3*@15) */
  w15  = (w03*w15);
  /* #104: output[1][26] = @15 */
  if (res[1]) res[1][26] = w15;
  /* #105: output[1][27] = @6 */
  if (res[1]) res[1][27] = w06;
  /* #106: @2 = (@1*@2) */
  w02  = (w01*w02);
  /* #107: @2 = (@4*@2) */
  w02  = (w04*w02);
  /* #108: @2 = (@3*@2) */
  w02  = (w03*w02);
  /* #109: @2 = (-@2) */
  w02 = (- w02 );
  /* #110: output[1][28] = @2 */
  if (res[1]) res[1][28] = w02;
  /* #111: output[1][29] = @16 */
  if (res[1]) res[1][29] = w16;
  /* #112: {NULL, @16, NULL, @2, @6, @15, NULL} = vertsplit(@14) */
  w16 = wr14[1];
  w02 = wr14[3];
  w06 = wr14[4];
  w15 = wr14[5];
  /* #113: output[1][30] = @16 */
  if (res[1]) res[1][30] = w16;
  /* #114: @16 = (@0*@6) */
  w16  = (w00*w06);
  /* #115: @16 = (@4*@16) */
  w16  = (w04*w16);
  /* #116: @16 = (@3*@16) */
  w16  = (w03*w16);
  /* #117: output[1][31] = @16 */
  if (res[1]) res[1][31] = w16;
  /* #118: output[1][32] = @2 */
  if (res[1]) res[1][32] = w02;
  /* #119: @6 = (@1*@6) */
  w06  = (w01*w06);
  /* #120: @6 = (@4*@6) */
  w06  = (w04*w06);
  /* #121: @6 = (@3*@6) */
  w06  = (w03*w06);
  /* #122: @6 = (-@6) */
  w06 = (- w06 );
  /* #123: output[1][33] = @6 */
  if (res[1]) res[1][33] = w06;
  /* #124: output[1][34] = @15 */
  if (res[1]) res[1][34] = w15;
  /* #125: @14 = zeros(3x7,7nz) */
  casadi_clear(w14, 7);
  /* #126: @17 = 00 */
  /* #127: @18 = ones(3x1,2nz) */
  casadi_fill(w18, 2, 1.);
  /* #128: {@15, NULL, @6} = vertsplit(@18) */
  w15 = w18[0];
  w06 = w18[1];
  /* #129: @2 = (@1*@15) */
  w02  = (w01*w15);
  /* #130: @2 = (@3*@2) */
  w02  = (w03*w02);
  /* #131: @16 = (@0*@15) */
  w16  = (w00*w15);
  /* #132: @16 = (@3*@16) */
  w16  = (w03*w16);
  /* #133: @19 = 0.707107 */
  w19 = 7.0710678118654746e-01;
  /* #134: @20 = 71428.6 */
  w20 = 7.1428571428571435e+04;
  /* #135: @15 = (@5*@15) */
  w15  = (w05*w15);
  /* #136: @15 = (@20*@15) */
  w15  = (w20*w15);
  /* #137: @15 = (@19*@15) */
  w15  = (w19*w15);
  /* #138: @15 = (-@15) */
  w15 = (- w15 );
  /* #139: @21 = vertcat(@17, @2, @17, @16, @17, @15, @6) */
  rr=w21;
  *rr++ = w02;
  *rr++ = w16;
  *rr++ = w15;
  *rr++ = w06;
  /* #140: @22 = @21[:4] */
  for (rr=w22, cs=w21+0; cs!=w21+4; cs+=1) *rr++ = *cs;
  /* #141: (@14[:8:2] = @22) */
  for (rr=w14+0, cs=w22; rr!=w14+8; rr+=2) *rr = *cs++;
  /* #142: @2 = ones(3x1,1nz) */
  w02 = 1.;
  /* #143: {NULL, @16, NULL} = vertsplit(@2) */
  w16 = w02;
  /* #144: @2 = (@1*@16) */
  w02  = (w01*w16);
  /* #145: @2 = (@3*@2) */
  w02  = (w03*w02);
  /* #146: @15 = (@0*@16) */
  w15  = (w00*w16);
  /* #147: @15 = (@3*@15) */
  w15  = (w03*w15);
  /* #148: @5 = (@5*@16) */
  w05 *= w16;
  /* #149: @20 = (@20*@5) */
  w20 *= w05;
  /* #150: @19 = (@19*@20) */
  w19 *= w20;
  /* #151: @23 = vertcat(@17, @2, @17, @15, @17, @19, @17) */
  rr=w23;
  *rr++ = w02;
  *rr++ = w15;
  *rr++ = w19;
  /* #152: @24 = @23[:3] */
  for (rr=w24, cs=w23+0; cs!=w23+3; cs+=1) *rr++ = *cs;
  /* #153: (@14[1:7:2] = @24) */
  for (rr=w14+1, cs=w24; rr!=w14+7; rr+=2) *rr = *cs++;
  /* #154: @13 = @14' */
  casadi_trans(w14,casadi_s1, w13, casadi_s0, iw);
  /* #155: @25 = project(@13) */
  casadi_project(w13, casadi_s0, w25, casadi_s2, w);
  /* #156: @26 = input[2][0] */
  wr26 = arg[2] ? arg[2] : casadi_zeros;
  /* #157: {@13, @14, @12} = horzsplit(@26) */
  wr13 = wr26;
  wr14 = wr26+7;
  wr12 = wr26+14;
  /* #158: {NULL, @2, NULL, @15, @19, @20, NULL} = vertsplit(@13) */
  w02 = wr13[1];
  w15 = wr13[3];
  w19 = wr13[4];
  w20 = wr13[5];
  /* #159: @5 = (@0*@19) */
  w05  = (w00*w19);
  /* #160: @5 = (@4*@5) */
  w05  = (w04*w05);
  /* #161: @5 = (@3*@5) */
  w05  = (w03*w05);
  /* #162: @19 = (@1*@19) */
  w19  = (w01*w19);
  /* #163: @19 = (@4*@19) */
  w19  = (w04*w19);
  /* #164: @19 = (@3*@19) */
  w19  = (w03*w19);
  /* #165: @19 = (-@19) */
  w19 = (- w19 );
  /* #166: @27 = vertcat(@2, @5, @15, @19, @20, @17, @17) */
  rr=w27;
  *rr++ = w02;
  *rr++ = w05;
  *rr++ = w15;
  *rr++ = w19;
  *rr++ = w20;
  /* #167: {NULL, @2, NULL, @5, @15, @19, NULL} = vertsplit(@14) */
  w02 = wr14[1];
  w05 = wr14[3];
  w15 = wr14[4];
  w19 = wr14[5];
  /* #168: @20 = (@0*@15) */
  w20  = (w00*w15);
  /* #169: @20 = (@4*@20) */
  w20  = (w04*w20);
  /* #170: @20 = (@3*@20) */
  w20  = (w03*w20);
  /* #171: @15 = (@1*@15) */
  w15  = (w01*w15);
  /* #172: @15 = (@4*@15) */
  w15  = (w04*w15);
  /* #173: @15 = (@3*@15) */
  w15  = (w03*w15);
  /* #174: @15 = (-@15) */
  w15 = (- w15 );
  /* #175: @28 = vertcat(@2, @20, @5, @15, @19, @17, @17) */
  rr=w28;
  *rr++ = w02;
  *rr++ = w20;
  *rr++ = w05;
  *rr++ = w15;
  *rr++ = w19;
  /* #176: {NULL, @2, NULL, @20, @5, @15, NULL} = vertsplit(@12) */
  w02 = wr12[1];
  w20 = wr12[3];
  w05 = wr12[4];
  w15 = wr12[5];
  /* #177: @0 = (@0*@5) */
  w00 *= w05;
  /* #178: @0 = (@4*@0) */
  w00  = (w04*w00);
  /* #179: @0 = (@3*@0) */
  w00  = (w03*w00);
  /* #180: @1 = (@1*@5) */
  w01 *= w05;
  /* #181: @4 = (@4*@1) */
  w04 *= w01;
  /* #182: @3 = (@3*@4) */
  w03 *= w04;
  /* #183: @3 = (-@3) */
  w03 = (- w03 );
  /* #184: @29 = vertcat(@2, @0, @20, @3, @15, @17, @17) */
  rr=w29;
  *rr++ = w02;
  *rr++ = w00;
  *rr++ = w20;
  *rr++ = w03;
  *rr++ = w15;
  /* #185: @30 = horzcat(@27, @28, @29) */
  rr=w30;
  for (i=0, cs=w27; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<5; ++i) *rr++ = *cs++;
  /* #186: @31 = project(@30) */
  casadi_project(w30, casadi_s3, w31, casadi_s2, w);
  /* #187: @25 = (@25+@31) */
  for (i=0, rr=w25, cs=w31; i<18; ++i) (*rr++) += (*cs++);
  /* #188: output[2][0] = @25 */
  casadi_copy(w25, 18, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mpcc_2d_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mpcc_2d_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_mpcc_2d_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mpcc_2d_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mpcc_2d_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mpcc_2d_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mpcc_2d_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s9;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 219;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 10*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 4*sizeof(casadi_int);
  if (sz_w) *sz_w = 219*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
