/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_mpcc_2d_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};
static const casadi_int casadi_s3[11] = 
  {10, 1, 0, 7, 1, 3, 4, 5,
  7, 8, 9};

/* quadrotor_mpcc_2d_expl_vde_adj:(i0[7],i1[7],i2[3],i3[4])->(o0[10x1,7nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *w00=w+0, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 7, w00);
  /* #1: {@1, @2, @3, @4, @5, @6, @7} = vertsplit(@0) */
  w01 = w00[0];
  w02 = w00[1];
  w03 = w00[2];
  w04 = w00[3];
  w05 = w00[4];
  w06 = w00[5];
  w07 = w00[6];
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #3: output[0][1] = @3 */
  if (res[0]) res[0][1] = w03;
  /* #4: @3 = input[0][4] */
  w03 = arg[0] ? arg[0][4] : 0;
  /* #5: @1 = cos(@3) */
  w01 = cos( w03 );
  /* #6: @8 = input[2][0] */
  w08 = arg[2] ? arg[2][0] : 0;
  /* #7: @9 = input[2][1] */
  w09 = arg[2] ? arg[2][1] : 0;
  /* #8: @8 = (@8+@9) */
  w08 += w09;
  /* #9: @9 = 37.037 */
  w09 = 3.7037037037037038e+01;
  /* #10: @2 = (@9*@2) */
  w02  = (w09*w02);
  /* #11: @10 = (@8*@2) */
  w10  = (w08*w02);
  /* #12: @10 = (@1*@10) */
  w10  = (w01*w10);
  /* #13: @3 = sin(@3) */
  w03 = sin( w03 );
  /* #14: @9 = (@9*@4) */
  w09 *= w04;
  /* #15: @8 = (@8*@9) */
  w08 *= w09;
  /* #16: @8 = (@3*@8) */
  w08  = (w03*w08);
  /* #17: @10 = (@10-@8) */
  w10 -= w08;
  /* #18: output[0][2] = @10 */
  if (res[0]) res[0][2] = w10;
  /* #19: output[0][3] = @5 */
  if (res[0]) res[0][3] = w05;
  /* #20: @1 = (@1*@9) */
  w01 *= w09;
  /* #21: @9 = 0.0397 */
  w09 = 3.9699999999999999e-02;
  /* #22: @5 = 71428.6 */
  w05 = 7.1428571428571435e+04;
  /* #23: @10 = 0.707107 */
  w10 = 7.0710678118654746e-01;
  /* #24: @10 = (@10*@6) */
  w10 *= w06;
  /* #25: @5 = (@5*@10) */
  w05 *= w10;
  /* #26: @9 = (@9*@5) */
  w09 *= w05;
  /* #27: @5 = (@1-@9) */
  w05  = (w01-w09);
  /* #28: @3 = (@3*@2) */
  w03 *= w02;
  /* #29: @5 = (@5+@3) */
  w05 += w03;
  /* #30: output[0][4] = @5 */
  if (res[0]) res[0][4] = w05;
  /* #31: @9 = (@9+@1) */
  w09 += w01;
  /* #32: @9 = (@9+@3) */
  w09 += w03;
  /* #33: output[0][5] = @9 */
  if (res[0]) res[0][5] = w09;
  /* #34: output[0][6] = @7 */
  if (res[0]) res[0][6] = w07;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mpcc_2d_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mpcc_2d_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_mpcc_2d_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mpcc_2d_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mpcc_2d_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mpcc_2d_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mpcc_2d_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 17;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 17*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
