/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[9] = 
  {10, 1, 0, 5, 0, 1, 2, 3,
  5};
static const casadi_int casadi_s1[3] = {7, 1, 1};
static const casadi_int casadi_s2[3] = {3, 1, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};
static const casadi_int casadi_s4[3] = {4, 1, 1};
static const casadi_int casadi_s5[3] = {1, 1, 1};
static const casadi_int casadi_s6[3] = {10, 1, 1};

/* quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac:(i0[7],i1[3],i2[0],i3[4])->(o0,o1[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real *w12=w+11, *w13=w+16;
  /* #0: @0 = 30 */
  w00 = 30.;
  /* #1: @1 = input[0][2] */
  w01 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = input[3][1] */
  w02 = arg[3] ? arg[3][1] : 0;
  /* #3: @1 = (@1-@2) */
  w01 -= w02;
  /* #4: @2 = input[3][2] */
  w02 = arg[3] ? arg[3][2] : 0;
  /* #5: @3 = (@1*@2) */
  w03  = (w01*w02);
  /* #6: @4 = input[0][0] */
  w04 = arg[0] ? arg[0][0] : 0;
  /* #7: @5 = input[3][0] */
  w05 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4-@5) */
  w04 -= w05;
  /* #9: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #10: @6 = (@4*@5) */
  w06  = (w04*w05);
  /* #11: @3 = (@3-@6) */
  w03 -= w06;
  /* #12: @6 = sq(@3) */
  w06 = casadi_sq( w03 );
  /* #13: @6 = (@0*@6) */
  w06  = (w00*w06);
  /* #14: @7 = 750 */
  w07 = 750.;
  /* #15: @4 = (@4*@2) */
  w04 *= w02;
  /* #16: @1 = (@1*@5) */
  w01 *= w05;
  /* #17: @4 = (@4+@1) */
  w04 += w01;
  /* #18: @1 = sq(@4) */
  w01 = casadi_sq( w04 );
  /* #19: @1 = (@7*@1) */
  w01  = (w07*w01);
  /* #20: @6 = (@6+@1) */
  w06 += w01;
  /* #21: @1 = 0.01 */
  w01 = 1.0000000000000000e-02;
  /* #22: @8 = input[1][2] */
  w08 = arg[1] ? arg[1][2] : 0;
  /* #23: @1 = (@1*@8) */
  w01 *= w08;
  /* #24: @6 = (@6-@1) */
  w06 -= w01;
  /* #25: @1 = 10 */
  w01 = 10.;
  /* #26: @8 = input[1][0] */
  w08 = arg[1] ? arg[1][0] : 0;
  /* #27: @9 = 0.1323 */
  w09 = 1.3230000000000000e-01;
  /* #28: @8 = (@8-@9) */
  w08 -= w09;
  /* #29: @10 = sq(@8) */
  w10 = casadi_sq( w08 );
  /* #30: @10 = (@1*@10) */
  w10  = (w01*w10);
  /* #31: @6 = (@6+@10) */
  w06 += w10;
  /* #32: @10 = input[1][1] */
  w10 = arg[1] ? arg[1][1] : 0;
  /* #33: @10 = (@10-@9) */
  w10 -= w09;
  /* #34: @9 = sq(@10) */
  w09 = casadi_sq( w10 );
  /* #35: @9 = (@1*@9) */
  w09  = (w01*w09);
  /* #36: @6 = (@6+@9) */
  w06 += w09;
  /* #37: output[0][0] = @6 */
  if (res[0]) res[0][0] = w06;
  /* #38: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #39: @8 = (@1*@8) */
  w08  = (w01*w08);
  /* #40: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #41: @1 = (@1*@10) */
  w01 *= w10;
  /* #42: @10 = -0.01 */
  w10 = -1.0000000000000000e-02;
  /* #43: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #44: @7 = (@7*@4) */
  w07 *= w04;
  /* #45: @4 = (@2*@7) */
  w04  = (w02*w07);
  /* #46: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #47: @0 = (@0*@3) */
  w00 *= w03;
  /* #48: @3 = (@5*@0) */
  w03  = (w05*w00);
  /* #49: @4 = (@4-@3) */
  w04 -= w03;
  /* #50: @11 = 00 */
  /* #51: @5 = (@5*@7) */
  w05 *= w07;
  /* #52: @2 = (@2*@0) */
  w02 *= w00;
  /* #53: @5 = (@5+@2) */
  w05 += w02;
  /* #54: @12 = vertcat(@8, @1, @10, @4, @11, @5, @11, @11, @11, @11) */
  rr=w12;
  *rr++ = w08;
  *rr++ = w01;
  *rr++ = w10;
  *rr++ = w04;
  *rr++ = w05;
  /* #55: @13 = dense(@12) */
  casadi_densify(w12, casadi_s0, w13, 0);
  /* #56: output[1][0] = @13 */
  casadi_copy(w13, 10, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 26;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 26*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
