/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_mpcc_2d_cost_ext_cost_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {4, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

/* quadrotor_mpcc_2d_cost_ext_cost_fun:(i0[7],i1[3],i2[0],i3[4])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6;
  /* #0: @0 = 30 */
  w0 = 30.;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = input[3][1] */
  w2 = arg[3] ? arg[3][1] : 0;
  /* #3: @1 = (@1-@2) */
  w1 -= w2;
  /* #4: @2 = input[3][2] */
  w2 = arg[3] ? arg[3][2] : 0;
  /* #5: @3 = (@1*@2) */
  w3  = (w1*w2);
  /* #6: @4 = input[0][0] */
  w4 = arg[0] ? arg[0][0] : 0;
  /* #7: @5 = input[3][0] */
  w5 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4-@5) */
  w4 -= w5;
  /* #9: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #10: @6 = (@4*@5) */
  w6  = (w4*w5);
  /* #11: @3 = (@3-@6) */
  w3 -= w6;
  /* #12: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #13: @0 = (@0*@3) */
  w0 *= w3;
  /* #14: @3 = 750 */
  w3 = 750.;
  /* #15: @4 = (@4*@2) */
  w4 *= w2;
  /* #16: @1 = (@1*@5) */
  w1 *= w5;
  /* #17: @4 = (@4+@1) */
  w4 += w1;
  /* #18: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #19: @3 = (@3*@4) */
  w3 *= w4;
  /* #20: @0 = (@0+@3) */
  w0 += w3;
  /* #21: @3 = 0.01 */
  w3 = 1.0000000000000000e-02;
  /* #22: @4 = input[1][2] */
  w4 = arg[1] ? arg[1][2] : 0;
  /* #23: @3 = (@3*@4) */
  w3 *= w4;
  /* #24: @0 = (@0-@3) */
  w0 -= w3;
  /* #25: @3 = 10 */
  w3 = 10.;
  /* #26: @4 = input[1][0] */
  w4 = arg[1] ? arg[1][0] : 0;
  /* #27: @1 = 0.1323 */
  w1 = 1.3230000000000000e-01;
  /* #28: @4 = (@4-@1) */
  w4 -= w1;
  /* #29: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #30: @4 = (@3*@4) */
  w4  = (w3*w4);
  /* #31: @0 = (@0+@4) */
  w0 += w4;
  /* #32: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #33: @4 = (@4-@1) */
  w4 -= w1;
  /* #34: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #35: @3 = (@3*@4) */
  w3 *= w4;
  /* #36: @0 = (@0+@3) */
  w0 += w3;
  /* #37: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_cost_ext_cost_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_cost_ext_cost_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_cost_ext_cost_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_cost_ext_cost_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mpcc_2d_cost_ext_cost_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mpcc_2d_cost_ext_cost_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_mpcc_2d_cost_ext_cost_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mpcc_2d_cost_ext_cost_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mpcc_2d_cost_ext_cost_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mpcc_2d_cost_ext_cost_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mpcc_2d_cost_ext_cost_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 7;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 7*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
