/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = 
  {10, 1, 0, 5, 0, 1, 2, 3,
  5};
static const casadi_int casadi_s1[4] = {0, 1, 2, 4};
static const casadi_int casadi_s2[19] = 
  {10, 10, 0, 1, 2, 2, 4, 4,
  6, 6, 6, 6, 6, 0, 1, 3,
  5, 3, 5};
static const casadi_int casadi_s3[3] = {7, 1, 1};
static const casadi_int casadi_s4[3] = {3, 1, 1};
static const casadi_int casadi_s5[3] = {0, 1, 1};
static const casadi_int casadi_s6[3] = {4, 1, 1};
static const casadi_int casadi_s7[3] = {1, 1, 1};
static const casadi_int casadi_s8[3] = {10, 1, 1};
static const casadi_int casadi_s9[3] = {0, 0, 1};
static const casadi_int casadi_s10[3] = {0, 10, 1};

/* quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess:(i0[7],i1[3],i2[0],i3[4])->(o0,o1[10],o2[10x10,6nz],o3[],o4[0x10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, *w13=w+12, *w14=w+17, *w15=w+27, *w16=w+33, *w17=w+42, *w18=w+46, *w19=w+50, *w20=w+52, *w21=w+54;
  const casadi_int *cii;
  const casadi_real *cs;
  /* #0: @0 = 30 */
  w00 = 30.;
  /* #1: @1 = input[0][2] */
  w01 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = input[3][1] */
  w02 = arg[3] ? arg[3][1] : 0;
  /* #3: @1 = (@1-@2) */
  w01 -= w02;
  /* #4: @2 = input[3][2] */
  w02 = arg[3] ? arg[3][2] : 0;
  /* #5: @3 = (@1*@2) */
  w03  = (w01*w02);
  /* #6: @4 = input[0][0] */
  w04 = arg[0] ? arg[0][0] : 0;
  /* #7: @5 = input[3][0] */
  w05 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4-@5) */
  w04 -= w05;
  /* #9: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #10: @6 = (@4*@5) */
  w06  = (w04*w05);
  /* #11: @3 = (@3-@6) */
  w03 -= w06;
  /* #12: @6 = sq(@3) */
  w06 = casadi_sq( w03 );
  /* #13: @6 = (@0*@6) */
  w06  = (w00*w06);
  /* #14: @7 = 750 */
  w07 = 750.;
  /* #15: @4 = (@4*@2) */
  w04 *= w02;
  /* #16: @1 = (@1*@5) */
  w01 *= w05;
  /* #17: @4 = (@4+@1) */
  w04 += w01;
  /* #18: @1 = sq(@4) */
  w01 = casadi_sq( w04 );
  /* #19: @1 = (@7*@1) */
  w01  = (w07*w01);
  /* #20: @6 = (@6+@1) */
  w06 += w01;
  /* #21: @1 = 0.01 */
  w01 = 1.0000000000000000e-02;
  /* #22: @8 = input[1][2] */
  w08 = arg[1] ? arg[1][2] : 0;
  /* #23: @1 = (@1*@8) */
  w01 *= w08;
  /* #24: @6 = (@6-@1) */
  w06 -= w01;
  /* #25: @1 = 10 */
  w01 = 10.;
  /* #26: @8 = input[1][0] */
  w08 = arg[1] ? arg[1][0] : 0;
  /* #27: @9 = 0.1323 */
  w09 = 1.3230000000000000e-01;
  /* #28: @8 = (@8-@9) */
  w08 -= w09;
  /* #29: @10 = sq(@8) */
  w10 = casadi_sq( w08 );
  /* #30: @10 = (@1*@10) */
  w10  = (w01*w10);
  /* #31: @6 = (@6+@10) */
  w06 += w10;
  /* #32: @10 = input[1][1] */
  w10 = arg[1] ? arg[1][1] : 0;
  /* #33: @10 = (@10-@9) */
  w10 -= w09;
  /* #34: @9 = sq(@10) */
  w09 = casadi_sq( w10 );
  /* #35: @9 = (@1*@9) */
  w09  = (w01*w09);
  /* #36: @6 = (@6+@9) */
  w06 += w09;
  /* #37: output[0][0] = @6 */
  if (res[0]) res[0][0] = w06;
  /* #38: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #39: @8 = (@1*@8) */
  w08  = (w01*w08);
  /* #40: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #41: @10 = (@1*@10) */
  w10  = (w01*w10);
  /* #42: @6 = -0.01 */
  w06 = -1.0000000000000000e-02;
  /* #43: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #44: @4 = (@7*@4) */
  w04  = (w07*w04);
  /* #45: @9 = (@2*@4) */
  w09  = (w02*w04);
  /* #46: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #47: @3 = (@0*@3) */
  w03  = (w00*w03);
  /* #48: @11 = (@5*@3) */
  w11  = (w05*w03);
  /* #49: @9 = (@9-@11) */
  w09 -= w11;
  /* #50: @12 = 00 */
  /* #51: @4 = (@5*@4) */
  w04  = (w05*w04);
  /* #52: @3 = (@2*@3) */
  w03  = (w02*w03);
  /* #53: @4 = (@4+@3) */
  w04 += w03;
  /* #54: @13 = vertcat(@8, @10, @6, @9, @12, @4, @12, @12, @12, @12) */
  rr=w13;
  *rr++ = w08;
  *rr++ = w10;
  *rr++ = w06;
  *rr++ = w09;
  *rr++ = w04;
  /* #55: @14 = dense(@13) */
  casadi_densify(w13, casadi_s0, w14, 0);
  /* #56: output[1][0] = @14 */
  casadi_copy(w14, 10, res[1]);
  /* #57: @15 = zeros(10x10,6nz) */
  casadi_clear(w15, 6);
  /* #58: @16 = ones(10x1,9nz) */
  casadi_fill(w16, 9, 1.);
  /* #59: {@8, @10, NULL, @6, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@16) */
  w08 = w16[0];
  w10 = w16[1];
  w06 = w16[3];
  /* #60: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #61: @8 = (@1*@8) */
  w08  = (w01*w08);
  /* #62: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #63: @1 = (@1*@10) */
  w01 *= w10;
  /* #64: @10 = (@2*@6) */
  w10  = (w02*w06);
  /* #65: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #66: @10 = (@7*@10) */
  w10  = (w07*w10);
  /* #67: @9 = (@2*@10) */
  w09  = (w02*w10);
  /* #68: @6 = (@5*@6) */
  w06  = (w05*w06);
  /* #69: @6 = (-@6) */
  w06 = (- w06 );
  /* #70: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #71: @6 = (@0*@6) */
  w06  = (w00*w06);
  /* #72: @4 = (@5*@6) */
  w04  = (w05*w06);
  /* #73: @9 = (@9-@4) */
  w09 -= w04;
  /* #74: @10 = (@5*@10) */
  w10  = (w05*w10);
  /* #75: @6 = (@2*@6) */
  w06  = (w02*w06);
  /* #76: @10 = (@10+@6) */
  w10 += w06;
  /* #77: @17 = vertcat(@8, @1, @12, @9, @12, @10, @12, @12, @12, @12) */
  rr=w17;
  *rr++ = w08;
  *rr++ = w01;
  *rr++ = w09;
  *rr++ = w10;
  /* #78: @18 = @17[:4] */
  for (rr=w18, cs=w17+0; cs!=w17+4; cs+=1) *rr++ = *cs;
  /* #79: (@15[:4] = @18) */
  for (rr=w15+0, cs=w18; rr!=w15+4; rr+=1) *rr = *cs++;
  /* #80: (@15[0, 1, 2, 4] = @18) */
  for (cii=casadi_s1, rr=w15, cs=w18; cii!=casadi_s1+4; ++cii, ++cs) rr[*cii] = *cs;
  /* #81: @8 = ones(10x1,1nz) */
  w08 = 1.;
  /* #82: {NULL, NULL, NULL, NULL, NULL, @1, NULL, NULL, NULL, NULL} = vertsplit(@8) */
  w01 = w08;
  /* #83: @8 = (@5*@1) */
  w08  = (w05*w01);
  /* #84: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #85: @7 = (@7*@8) */
  w07 *= w08;
  /* #86: @8 = (@2*@7) */
  w08  = (w02*w07);
  /* #87: @1 = (@2*@1) */
  w01  = (w02*w01);
  /* #88: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #89: @0 = (@0*@1) */
  w00 *= w01;
  /* #90: @1 = (@5*@0) */
  w01  = (w05*w00);
  /* #91: @8 = (@8-@1) */
  w08 -= w01;
  /* #92: @5 = (@5*@7) */
  w05 *= w07;
  /* #93: @2 = (@2*@0) */
  w02 *= w00;
  /* #94: @5 = (@5+@2) */
  w05 += w02;
  /* #95: @19 = vertcat(@12, @12, @12, @8, @12, @5, @12, @12, @12, @12) */
  rr=w19;
  *rr++ = w08;
  *rr++ = w05;
  /* #96: @20 = @19[:2] */
  for (rr=w20, cs=w19+0; cs!=w19+2; cs+=1) *rr++ = *cs;
  /* #97: (@15[4:6] = @20) */
  for (rr=w15+4, cs=w20; rr!=w15+6; rr+=1) *rr = *cs++;
  /* #98: (@15[3:7:2] = @20) */
  for (rr=w15+3, cs=w20; rr!=w15+7; rr+=2) *rr = *cs++;
  /* #99: @21 = @15' */
  casadi_trans(w15,casadi_s2, w21, casadi_s2, iw);
  /* #100: output[2][0] = @21 */
  casadi_copy(w21, 6, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s2;
    case 3: return casadi_s9;
    case 4: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 15;
  if (sz_iw) *sz_iw = 11;
  if (sz_w) *sz_w = 60;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_0_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 15*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 11*sizeof(casadi_int);
  if (sz_w) *sz_w = 60*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
