/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[6] = {7, 1, 0, 2, 0, 2};
static const casadi_int casadi_s1[14] = 
  {7, 7, 0, 2, 2, 4, 4, 4,
  4, 4, 0, 2, 0, 2};
static const casadi_int casadi_s2[3] = {7, 1, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};
static const casadi_int casadi_s4[3] = {4, 1, 1};
static const casadi_int casadi_s5[3] = {1, 1, 1};
static const casadi_int casadi_s6[3] = {0, 0, 1};
static const casadi_int casadi_s7[3] = {0, 7, 1};

/* quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess:(i0[7],i1[0],i2[0],i3[4])->(o0,o1[7],o2[7x7,4nz],o3[],o4[0x7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, *w09=w+8, *w10=w+10, *w11=w+17;
  casadi_real *w12=w+21, *w13=w+27, *w14=w+29;
  const casadi_real *cs;
  /* #0: @0 = 60 */
  w00 = 60.;
  /* #1: @1 = input[0][2] */
  w01 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = input[3][1] */
  w02 = arg[3] ? arg[3][1] : 0;
  /* #3: @1 = (@1-@2) */
  w01 -= w02;
  /* #4: @2 = input[3][2] */
  w02 = arg[3] ? arg[3][2] : 0;
  /* #5: @3 = (@1*@2) */
  w03  = (w01*w02);
  /* #6: @4 = input[0][0] */
  w04 = arg[0] ? arg[0][0] : 0;
  /* #7: @5 = input[3][0] */
  w05 = arg[3] ? arg[3][0] : 0;
  /* #8: @4 = (@4-@5) */
  w04 -= w05;
  /* #9: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #10: @6 = (@4*@5) */
  w06  = (w04*w05);
  /* #11: @3 = (@3-@6) */
  w03 -= w06;
  /* #12: @6 = sq(@3) */
  w06 = casadi_sq( w03 );
  /* #13: @6 = (@0*@6) */
  w06  = (w00*w06);
  /* #14: @7 = 1500 */
  w07 = 1500.;
  /* #15: @4 = (@4*@2) */
  w04 *= w02;
  /* #16: @1 = (@1*@5) */
  w01 *= w05;
  /* #17: @4 = (@4+@1) */
  w04 += w01;
  /* #18: @1 = sq(@4) */
  w01 = casadi_sq( w04 );
  /* #19: @1 = (@7*@1) */
  w01  = (w07*w01);
  /* #20: @6 = (@6+@1) */
  w06 += w01;
  /* #21: output[0][0] = @6 */
  if (res[0]) res[0][0] = w06;
  /* #22: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #23: @4 = (@7*@4) */
  w04  = (w07*w04);
  /* #24: @6 = (@2*@4) */
  w06  = (w02*w04);
  /* #25: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #26: @3 = (@0*@3) */
  w03  = (w00*w03);
  /* #27: @1 = (@5*@3) */
  w01  = (w05*w03);
  /* #28: @6 = (@6-@1) */
  w06 -= w01;
  /* #29: @8 = 00 */
  /* #30: @4 = (@5*@4) */
  w04  = (w05*w04);
  /* #31: @3 = (@2*@3) */
  w03  = (w02*w03);
  /* #32: @4 = (@4+@3) */
  w04 += w03;
  /* #33: @9 = vertcat(@6, @8, @4, @8, @8, @8, @8) */
  rr=w09;
  *rr++ = w06;
  *rr++ = w04;
  /* #34: @10 = dense(@9) */
  casadi_densify(w09, casadi_s0, w10, 0);
  /* #35: output[1][0] = @10 */
  casadi_copy(w10, 7, res[1]);
  /* #36: @11 = zeros(7x7,4nz) */
  casadi_clear(w11, 4);
  /* #37: @12 = ones(7x1,6nz) */
  casadi_fill(w12, 6, 1.);
  /* #38: {@6, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@12) */
  w06 = w12[0];
  /* #39: @4 = (@2*@6) */
  w04  = (w02*w06);
  /* #40: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #41: @4 = (@7*@4) */
  w04  = (w07*w04);
  /* #42: @3 = (@2*@4) */
  w03  = (w02*w04);
  /* #43: @6 = (@5*@6) */
  w06  = (w05*w06);
  /* #44: @6 = (-@6) */
  w06 = (- w06 );
  /* #45: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #46: @6 = (@0*@6) */
  w06  = (w00*w06);
  /* #47: @1 = (@5*@6) */
  w01  = (w05*w06);
  /* #48: @3 = (@3-@1) */
  w03 -= w01;
  /* #49: @4 = (@5*@4) */
  w04  = (w05*w04);
  /* #50: @6 = (@2*@6) */
  w06  = (w02*w06);
  /* #51: @4 = (@4+@6) */
  w04 += w06;
  /* #52: @9 = vertcat(@3, @8, @4, @8, @8, @8, @8) */
  rr=w09;
  *rr++ = w03;
  *rr++ = w04;
  /* #53: @13 = @9[:2] */
  for (rr=w13, cs=w09+0; cs!=w09+2; cs+=1) *rr++ = *cs;
  /* #54: (@11[:2] = @13) */
  for (rr=w11+0, cs=w13; rr!=w11+2; rr+=1) *rr = *cs++;
  /* #55: (@11[:4:2] = @13) */
  for (rr=w11+0, cs=w13; rr!=w11+4; rr+=2) *rr = *cs++;
  /* #56: @3 = ones(7x1,1nz) */
  w03 = 1.;
  /* #57: {NULL, NULL, @4, NULL, NULL, NULL, NULL} = vertsplit(@3) */
  w04 = w03;
  /* #58: @3 = (@5*@4) */
  w03  = (w05*w04);
  /* #59: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #60: @7 = (@7*@3) */
  w07 *= w03;
  /* #61: @3 = (@2*@7) */
  w03  = (w02*w07);
  /* #62: @4 = (@2*@4) */
  w04  = (w02*w04);
  /* #63: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #64: @0 = (@0*@4) */
  w00 *= w04;
  /* #65: @4 = (@5*@0) */
  w04  = (w05*w00);
  /* #66: @3 = (@3-@4) */
  w03 -= w04;
  /* #67: @5 = (@5*@7) */
  w05 *= w07;
  /* #68: @2 = (@2*@0) */
  w02 *= w00;
  /* #69: @5 = (@5+@2) */
  w05 += w02;
  /* #70: @13 = vertcat(@3, @8, @5, @8, @8, @8, @8) */
  rr=w13;
  *rr++ = w03;
  *rr++ = w05;
  /* #71: @9 = @13[:2] */
  for (rr=w09, cs=w13+0; cs!=w13+2; cs+=1) *rr++ = *cs;
  /* #72: (@11[2:4] = @9) */
  for (rr=w11+2, cs=w09; rr!=w11+4; rr+=1) *rr = *cs++;
  /* #73: (@11[1:5:2] = @9) */
  for (rr=w11+1, cs=w09; rr!=w11+5; rr+=2) *rr = *cs++;
  /* #74: @14 = @11' */
  casadi_trans(w11,casadi_s1, w14, casadi_s1, iw);
  /* #75: output[2][0] = @14 */
  casadi_copy(w14, 4, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    case 3: return casadi_s6;
    case 4: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 12;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 33;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_mpcc_2d_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 12*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 8*sizeof(casadi_int);
  if (sz_w) *sz_w = 33*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
